### ISSUE TITLE
Passive upload mode

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/HSBencher#75]
Basically, the proposal is to have a passive mode for the command line hsbencher tool.  Instead of *running* the benchmarks it would just read its stdin for benchmark data and upload it.  We already have similar things for uploading from files on disk (e.g. criterion reports)... this would do it live from stdin, something like:

```
  myscript | hsb upload --fromLog --fusion --codespeed ...
```

And to do that we'd need expand our vocabulary of "tags" to include some kind of start and end markers:

```
START_BENCHMARK
PROGNAME: foo
VARIANT:  x
SELFTIMED:  9.99
....
END_BENCHMARK
```

This would also solve our related problem of wanting to run a job via hsbencher, but report multiple, different benchmark results from a given subprocess execution.  (Like an entire criterion suite.)

**Comment by benjmart** [comment]
Any updates on this one?

**Comment by rrnewton** [comment]
It's next on my TODO list.  We should get to it soon.
